name: Run GHDL on MacOS X64

on:
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-13
    steps:
      - uses: dawidd6/action-download-artifact@v7
        with:
         repo: ghdl/ghdl
         workflow: Pipeline.yml
         run_number: 468
         name: ghdl-macos-13-x86_64-llvm
         path: /usr/local

