name: Run GHDL on Win64

on:
  workflow_dispatch:

jobs:

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-clang
      - uses: dawidd6/action-download-artifact@v3
        with:
         workflow: win_dev.yml
         workflow_conclusion: ""
         name: Dev, Windows 64-bit
         path: C:\Spice64
      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          cp div3.cir C:/Spice64/examples
          export PATH=$PATH:/mingw64/bin
          cd C:/Spice64/examples
          ls
          C:/Spice64/bin/ngspice ghnggen adc.vhd
          C:/Spice64/bin/ngspice -- ghnggen mc.vhd
          ../bin/ngspice -b -r adc.raw adc.cir
      - name: Test 2
        shell: cmd
        run: |
          echo %GHDL%
          C:
          cd \Spice64/examples
          copy D:\a\_temp\msys64\UCRT64\lib\libghdlvpi.dll .
          dir
          ..\bin\ngspice -b -r mc.raw mc.cir
          dir
          md results
          copy *.raw results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: C:\Spice64\examples\results

