name: Run GHDL on Win64

on:
  workflow_dispatch:

jobs:

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-clang
            mingw-w64-ucrt-x86_64-gcc-ada
            mingw-w64-ucrt-x86_64-llvm-libs
      - uses: dawidd6/action-download-artifact@v3
        with:
         workflow: win_dev.yml
         workflow_conclusion: ""
         name: Dev, Windows 64-bit
         path: C:\Spice64
      - uses: dawidd6/action-download-artifact@v7
        with:
         repo: ghdl/ghdl
         workflow: Pipeline.yml
         name: ghdl-MSYS2-ucrt64-llvm
         path: .
         skip_unpack: true
      - name: Unzip GHDL
        shell: cmd
        run: |
          7z x ghdl-MSYS2-ucrt64-llvm.zip
          dir
      - name: Untar GHDL
        run: |
          ls
          t=`pwd`
          mkdir /c/ghdl
          cd /c/ghdl
          tar xvf $t/__pyTooling_upload_artifact__.tar
          bin/ghdl help
      - name: Test 1
        run: |
          export PATH=$PATH:/mingw64/bin:/c/spice64/bin:/c/ghdl/bin
          cd /C/Spice64/examples/ghdl
          ls
          ngspice ghnggen adc.vhd
          ls
          cp /c/ghdl/lib/libghdlvpi.dll .
          ngspice -b -r adc.raw adc.cir
      - name: Test 2
        shell: cmd
        run: |
          C:
          cd \Spice64\examples\ghdl
          set PATH=%PATH%;c:\spice64\bin;c:\ghdl\bin
          ngspice ghnggen mc.vhd
          dir
          ngspice -b -r mc.raw mc.cir
          md results
          copy *.raw results
          .\clean
          dir
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: C:\Spice64\examples\ghdl\results

