name: Run GHDL on MacOS X64

on:
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - name: Install Dependencies
        run: |
          brew install libxaw libatomic_ops
      - uses: dawidd6/action-download-artifact@v7
        with:
         workflow: macos.yml
         name: Test Macos X86_64
         path: /usr/local
      - uses: dawidd6/action-download-artifact@v7
        with:
         repo: ghdl/ghdl
         workflow: Pipeline.yml
         name: ghdl-macos-13-x86_64-llvm
         path: .
         skip_unpack: true
      - name: Untar GHDL
        run: |
          ls
          unzip ghdl-macos-13-x86_64-llvm.zip
          t=`pwd`
          cd /usr/local
          tar xvf $t/__pyTooling_upload_artifact__.tar
          ghdl help
          chmod a+x bin/ngspice
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          cd /usr/local/share/ngspice/examples
          ls -l
          chmod a+x clean build
          ./build
          ngspice -b -r adc.raw adc.cir
      - name: Test 2
        run: |
          echo $GHDL
          cd /usr/local/share/ngspice/examples
          ngspice -b -r mc.raw mc.cir
          ls
          mkdir results
          cp *.raw results
          ./clean
          ls
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: /usr/local/share/ngspice/examples/results
