name: Run GHDL on MacOS X64

on:
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - name: Install Dependencies
        run: |
          brew install libxaw libatomic_ops
      - uses: dawidd6/action-download-artifact@v7
        with:
         workflow: macos.yml
         name: Test Macos X86_64
         path: /usr/local
      - uses: dawidd6/action-download-artifact@v7
        with:
         repo: ghdl/ghdl
         workflow: Pipeline.yml
         name: ghdl-macos-13-x86_64-llvm
         path: .
         skip_unpack: true
      - name: Untar GHDL
        run: |
          ls
          unzip ghdl-macos-13-x86_64-llvm.zip
          t=`pwd`
          cd /usr/local
          tar xvf $t/__pyTooling_upload_artifact__.tar
          ghdl help
          chmod a+x bin/ngspice
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          cp div3.cir /usr/local/share/ngspice/examples
          cd /usr/local/share/ngspice/examples
          ls
          ngspice -- ghnggen -top timer_core 555.vhd
          ngspice -- ghnggen -top wrapper div3.vhd
          ngspice -b -r div3.raw div3.cir
      - name: Test 2
        run: |
          echo $GHDL
          cd /usr/local/share/ngspice/examples
          ngspice -b -r 555.raw 555.cir
          ls
          md results
          copy *.raw results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: results

