name: Run GHDL on MacOS X64

on:
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-13
    strategy:
      fail-fast: false
    steps:
      - name: Install Dependencies
        run: |
          brew install libxaw libatomic_ops
      - uses: dawidd6/action-download-artifact@v7
        with:
         workflow: macos.yml
         run_number: 28
         name: Test Macos X86_64
         path: /usr/local
      - name: Test 0
        run: |
          otool -L /usr/local/bin/ngspice
      - uses: dawidd6/action-download-artifact@v7
        with:
         repo: ghdl/ghdl
         workflow: Pipeline.yml
         run_number: 468
         name: ghdl-macos-13-x86_64-llvm
         path: /usr/local
      - name: Untar GHDL
        run: |
          cd /usr/local
          tar xvf __pyTooling_upload_artifact__.tar
          ghdl help
      - uses: actions/checkout@v4
      - name: Test 1
        run: |
          ls
          ngspice -- ghnggen -top timer_core 555.vhd
          ngspice -- ghnggen -top wrapper div3.vhd
          ngspice -b -r div3.raw div3.cir
      - name: Test 2
        run: |
          echo $GHDL
          ngspice -b -r 555.raw 555.cir
          ls
          md results
          copy *.raw results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: results

