name: Test Homebrew env
on:
  workflow_dispatch:

jobs:
  check-darwin-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make libelf freeglut patchelf 
          brew tap osx-cross/avr
          brew install avr-gcc@8 avr-binutils
      - name: Test
        run: |
          echo _____ Files ______
          find /usr/local -name iom2560.h
          echo _____ Cellar ______
          ls /usr/local/Cellar

