name: Test Homebrew env
on:
  workflow_dispatch:

jobs:
  check-darwin-x64:
    # this is currently macos-11, Big Sur
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: | 
          brew install make libelf freeglut patchelf 
          brew tap osx-cross/avr
          brew install avr-gcc@8 avr-binutils
      - name: Test
        run: |
          echo _____ Files ______
          ls /usr/local/opt/
          echo _____ Programs ______
          export PATH="/usr/local/opt/avr-gcc@8/bin:/usr/local/opt/avr-binutils/bin:$PATH"
          which avr-objcopy
          which avr-gcc
          echo _____ Find Cellar ______
          find /usr/local -name Cellar

