name: Build MacOS
on:
  workflow_dispatch:

jobs:
  build-macos-X86_64:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - name: Install Dependencies
        run: |
          brew install make automake bison
          brew install libxaw
          # compile_macos_clang.sh expects this path.  Kludge it.
          sudo mkdir -p /opt/X11/include
          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
      - name: Build X86_64
        run: |
          PATH='/usr/local/opt/bison/bin:'$PATH
          ./autogen.sh
          mkdir releasesh
          cd releasesh
          ../configure  --disable-openmp --enable-cider --with-ngshared CC=clang CFLAGS="-m64 -O2"  LDFLAGS="-m64 -L/usr/local/lib"
          make -j3
          ls  src/.libs
          if [ ! -f src/.libs/libngspice.so ]; then false; fi
      - name: Install X86_64
        run: |
          cd release
          sudo make install
          cd ..
          mkdir build
          for i in bin lib share ; do
            mkdir -p build/$i
            cp -r /usr/local/$i/ngspice build/$i/
          done
          mkdir -p build/share/ngspice/examples/shared
          cp releasesh/src/.libs/libngspice.so build/lib/ngspice
          cp examples/shared/* build/share/ngspice/examples/shared
          ls -R build/share/ngspice/examples
      - name: Build shx.
        run: |
          cd examples/shared
          gcc -I../../src/include/ngspice -o shx shx.c
          mv shx ../../build/bin
      - name: Fail
        run: |
          false
          chmod a+x compile_macos_clang.sh
          ./compile_macos_clang.sh || true # Will fail to install
          if [ ! -f release/src/ngspice ]; then false; fi
      - name: Save X86_64
        uses: actions/upload-artifact@v4
        with:
          name: Test Macos X86_64
          path: build
