name: Build MacOS
on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - name: Install Dependencies
        run: |
          brew install make automake bison
          brew install ncurses libxaw libtool readline
          brew reinstall readline
          # compile_macos_clang.sh expects this path.  Kludge it.
          sudo mkdir -p /opt/X11/include
          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
          ls /opt/homebrew/Cellar/readline/8.2.13
      - name: Build Arm64
        run: |
          PATH='/usr/local/opt/bison/bin:'$PATH
          chmod a+x compile_macos_clang_M2.sh
          ./compile_macos_clang_M2.sh || true # Will fail to install
          if [ ! -f release/src/ngspice ]; then false; fi
      - name: Install Arm64
        run: |
          cd release
          sudo make install
          cd ..
          mkdir build
          for i in bin lib share ; do
            mkdir -p build/$i
            cp -r /usr/local/$i/ngspice build/$i/
          done
      - name: Save Arm64
        uses: actions/upload-artifact@v4
        with:
          name: Test Macos Arm64
          path: build
