name: Build master branch
on:
  workflow_dispatch:
  schedule:
    - cron: '41 7 9 1,3,5,7,9,11 *'

jobs:
  build-lin64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: master
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git make bison flex libtool autoconf automake libx11-dev libxaw7-dev libreadline-dev libxmu6 libxft2 libxrender1 libfreetype6 libfontconfig
      - name: Clean /usr/local
        run: |
          cd /usr
          sudo mv local l
          sudo mkdir -m777 local
      - name: Build
        run: |
          ./compile_linux_shared.sh
          ./compile_linux.sh
          mkdir releasesh
          cd releasesh
          ../configure --with-ngshared --enable-cider --prefix=/usr/local CFLAGS="-m64 -O2" LDFLAGS="-m64 -s"
          make -j4
          make install
          echo Create README.ngspice
          echo 'This binary package of an Ngspice release was built at https://github.com/gatk555/ngspice.' > /usr/local/README.ngspice
          echo 'The source code came from the master branch.' >> /usr/local/README.ngspice
          echo 'Install to /usr/local.' >> /usr/local/README.ngspice
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice-44.2, Linux X86-64
          path: /usr/local
