name: Build master branch
on:
  workflow_dispatch:

jobs:
  build-win_msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autotools
      - name: Flex and Bison
        shell: cmd
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: master
      - name: Build
        run: |
          ./compile_min.sh
          ldd release/src/ngspice.exe || true
          echo Create README.ngspice
          echo This binary build of ngspice was built at https://github.com/gatk555/ngspice. > C:\Spice64\README.ngspice
          echo The source code came from the master branch. >> C:\Spice64\README.ngspice
          echo Install to C:\Spice64\. >> C:\Spice64\README.ngspice
      - name: Probe requirements
        shell: cmd
        run: |
          dumpbin /dependents c:\spice64\bin\ngspice.exe

