name: Build others
on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_test
      - name: Install Dependencies
        run: |
          brew install automake libtool ncurses bison
          # compile_macos_gcc.sh expects this path.  Kludge it.
          sudo mkdir -p /opt/X11/include
          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
      - name: Build arm64
        run: |
          which gcc clang
          export PATH="/opt/homebrew/opt/bison/bin:$PATH"
          ./autogen.sh
          mkdir release
          cd release
          ../configure --with-x --enable-cider --with-readline=/opt/homebrew/opt/readline CC=gcc-14 CFLAGS="-m64 -O2 -I/opt/X11/include/freetype2 -I/opt/homebrew/opt/readline/include -I/opt/homebrew/opt/ncurses/include" LDFLAGS="-m64 -L/opt/homebrew/opt/readline/lib -L/opt/homebrew/opt/ncurses/lib -L/opt/X11/lib -L/usr/local/lib -lomp" || true
          make || true
          mkdir ../build
          cp config.log ../configure ../build
      - name: Save arm64
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice pre-master-45, Macos arm64
          path: build
      - name: Install arm64
        run: |
          if [ ! -f release/src/ngspice ]; then false; fi
          cd ..
          mkdir build
          for i in bin lib share ; do
            mkdir -p build/$i
            cp -r /usr/local/$i/ngspice build/$i/
          done
          echo Create README.ngspice
          echo 'This binary package of ngspice was built at https://github.com/gatk555/ngspice.' > build/README.ngspice
          echo 'The source code came from the pre-master-45 branch.' >> build/README.ngspice
          echo 'Install to /usr/local.' >> build/README.ngspice
