name: Test environment
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_pm45
      - name: Save SHA for Windows
        run: |
          echo $GITHUB_ENV
          echo Try it
          echo "HEAD_DESC=\"`git log -1 --pretty=oneline`\"" >> "$GITHUB_ENV"
          echo Test it
          echo ${{ env.HEAD_DESC }}
