name: Test 100W.sp
on:
  workflow_dispatch:

jobs:
  build-win_cygwin:
    runs-on: windows-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          repo: gatk555/ngspice
          workflow: others.yml
          name: Ngspice pre-master-45, Windows 64-bit with MSYS and UCRT64
          path: C:\Spice64
      - uses: actions/checkout@v3
      - name: Run
        run: |
          C:\spice64\bin\ngspice_con.exe 100W.sp
