name: Test ARM action
on:
  workflow_dispatch:

jobs:
  build-armv6l:
    runs-on: ubuntu-latest
    steps:
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: arm1176
          base_image: raspios_lite:latest
          copy_artifact_path: simavr.tar.gz
          image_additional_mb: 1024
          commands: |
            df -h /
            sudo apt-get update
            sudo apt-get install -y build-essential git make gcc-avr avr-libc libelf-dev freeglut3-dev patchelf file
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: pguyot/arm-runner-action@v2
        id: build_image
        with:
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          copy_artifact_path: simavr.tar.gz
          image_additional_mb: 1024
          commands: |
            df -h /
            sudo apt-get install -y build-essential git make gcc-avr avr-libc libelf-dev freeglut3-dev patchelf file
