# Probe VM
name: Link IVL DLLs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: win.yml
         workflow_conclusion: ""
         run_number: 2
         name: MINGW64-x86_64
         path: .
      - name: Install
        shell: msys2 {0}
        run: |
          pacman -U --noconfirm *.zst
          which vvp
      - name: Build
        shell: cmd
        run: |
          cd btest\a\b
          aux-ivl.bat
      - name: Build test.exe
        shell: cmd
        run: |
          cd vlog
          echo Testing components
          copy ..\btest\a\b\verilog\libvvp.lib .
          copy ..\btest\a\b\verilog\ivlng.lib .
          copy ..\btest\a\b\verilog\ivlng.dll .
          copy ..\btest\a\b\verilog\shim.vp ivlng.vpi
          CL.EXE /O2 /Fetest.exe  /I. test.c libvvp.lib ivlng.lib
          copy D:\a\_temp\msys64\mingw64\lib\libvvp.dll .
          dir
          echo ============ ivlng.dll ===============
          dumpbin /dependents ivlng.dll
          echo ============ shim.vpi ===============
          dumpbin /dependents shim.vpi
          echo ============ test.exe ===============
          dumpbin /dependents test.exe
      - name: Run in MSYS
        shell: msys2 {0}
        run: |
          cd vlog
          ls -l
          echo ============ libvvp.dll ===============
          ldd  libvvp.dll
          echo ============ ivlng.dll ===============
          ldd ivlng.dll
          echo ============ ivlng.vpi ===============
          file ivlng.vpi
          echo ============ test.exe ===============
          ldd test.exe
          echo ============ Run.exe ===============
          ./test.exe 555
