# Probe VM
name: Link IVL DLLs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: win_dev.yml
         workflow_conclusion: ""
         run_number: 2
         name: MINGW64-x86_64
         path: .
      - name: Build
        shell: cmd
        run: |
          pacman -U --noconfirm msys2/*.zst
          which vvp
          cd vlog
          CL.EXE /O2 /LD /EHsc /Feivlng.DLL /I. icarus_shim.c /link /EXPORT:Cosim_setup /EXPORT:Get_ng_vvp
          dir
          lib.exe /def:libvvp.def /machine:X64
          dir
          CL.EXE /O2 /LD /EHsc /Feivlng.vpi /I. vpi.c libvvp.lib ivlng.lib /link /DLL
          dir
          CL.EXE /O2 /Fetetst.exe  /I. test.c libvvp.lib ivlng.lib
          copy D:\a\_temp\msys64\mingw64\lib\libvvp.dll .
          test.exe
