# Probe VM
name: Test ngspice.exe
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Run
        shell: cmd
        run: |
          curl.exe -L -O https://aka.ms/vs/17/release/vc_redist.x64.exe
          ./vc_redist.x64.exe
          dir
