# Probe VM
name: Link IVL DLLs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: win.yml
         workflow_conclusion: ""
         run_number: 2
         name: MINGW64-x86_64
         path: .
      - name: Install
        shell: msys2 {0}
        run: |
          pacman -U --noconfirm *.zst
          which vvp
      - name: Build
        shell: cmd
        run: |
          cd vlog
          CL.EXE /O2 /LD /EHsc /Feivlng.DLL /I. icarus_shim.c /link /EXPORT:Cosim_setup /EXPORT:Get_ng_vvp
          dir
          lib.exe /def:libvvp.def /machine:X64
          dir
          CL.EXE /O2 /LD /EHsc /Feshim.vpi /I. vpi.c libvvp.lib ivlng.lib /link /DLL /EXPORT:vlog_startup_routines
          dir
          CL.EXE /O2 /Fetest.exe  /I. test.c libvvp.lib ivlng.lib
          copy D:\a\_temp\msys64\mingw64\lib\libvvp.dll .
          dir
          echo ============ ivlng.dll ===============
          dumpbin /dependents ivlng.dll
          echo ============ shim.vpi ===============
          dumpbin /dependents shim.vpi
          echo ============ test.exe ===============
          dumpbin /dependents test.exe
      - name: Run in MSYS
        shell: msys2 {0}
        run: |
          cd vlog
          mv shim.vpi ivlng.vpi
          ls -l
          echo ============ libvvp.dll ===============
          ldd  libvvp.dll
          echo ============ ivlng.dll ===============
          ldd ivlng.dll
          echo ============ ivlng.vpi ===============
          file ivlng.vpi
          echo ============ test.exe ===============
          ldd test.exe
          echo ============ Run.exe ===============
          ./test.exe 555
