name: Test 100W.sp
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
      - uses: dawidd6/action-download-artifact@v8
        with:
          repo: gatk555/test
          workflow: win_dev_msys.yml
          workflow_conclusion: ""
          name: Ngspice Test, Windows 64-bit with MSYS and UCRT64
          path: C:\Spice64
      - uses: actions/checkout@v3
      - name: Run in CMD
        run: |
          C:\spice64\bin\ngspice.exe  -o t.log 100W.sp
          type t.log
	  dir
      - name: Run in MSYS
        shell: msys2 {0}
        run: |
          echo Run it.
          /c/spice64/bin/ngspice -o t.log 100W.sp
          cat t.log
