# Probe VM
name: Link IVL DLLs
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: cmd
        run: |
          cd vlog
          CL.EXE /O2 /LD /EHsc /Fe ivlng.DLL /I. icarus_shim.c /link /EXPORT:Cosim_setup /EXPORT:Get_ng_vvp
          dir
          lib.exe /def:libvvp.def
          dir
          CL.EXE /O2 /LD /EHsc /Fe ivlng.DLL /I. vpi.c libvvp.lib /link /DLL
          dir

