# Probe bison on Windows
name: Probe
on:
  workflow_dispatch:

jobs:
  try_it:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: gh_test
      - name: Test
        shell: cmd
        run: |
          md tmp-bison
          dir
          ..\flex-bison\win_bison.exe --output=.\tmp-bison\parse_bison.c src\frontend\parse-bison.y
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Bison_output
          path: ./tmp-bison
