name: Build ngspice with CYGWIN
on:
  workflow_dispatch:

jobs:
  build-win_cygwin:
    runs-on: windows-2019
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr {0}
    steps:
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: gcc-g++ flex bison
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - name: Build
        run: |
          cd d:\\\\a\\\\test\\\\test
          chmod a+x *.sh
          ./compile_min.sh
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Test Ngspice, Windows 64-bit with CYGWIN
          path: C:\Spice64
