name: Run
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          location: d:\
          install: mingw-w64-x86_64-verilator
      - uses: dawidd6/action-download-artifact@v2
        with:
         workflow: test.yml
         run_number: 22
         name: Test, Windows 64-bit
         path: C:\Spice64_KLU
      - uses: actions/checkout@v3
      - name: Run
        shell: cmd
        run: |
          copy sogen.sp c:\Spice64_KLU\share\ngspice\verilog\verilator
          cd \
          C:
          set PATH=%PATH%;d:\msys64\mingw64\bin
          cd \Spice64_KLU\share\ngspice\verilog\verilator
          \Spice64_KLU\bin\ngspice -b -o log.txt sogen.sp ..\..\examples\xspice\verilog\adc.v
          dir
          type log.txt
          echo Running directly
          perl d:/msys64/mingw64/bin/verilator  --Mdir adc_obj_dir --prefix Vlng -I /d/msys64/mingw64/share/verilator/include --cc ../../examples/xspice/verilog/adc.v