name: Run
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
         workflow: test.yml
         name: Test, Windows 64-bit
         path: C:\Spice64_KLU
      - name: Run
        shell: cmd
        run: |
          DIR C:\Spice64_KLU
          C:
          cd \Spice64_KLU\share\ngspice\verilo\g\verilator
          \Spice64_KLU\bin\ngspice -b -o log.txt sogen.sp ..\..\examples\xspice\verilog\adc.v
          dir
          type log.txt
