name: Run
on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-verilator
      - name: Run
        shell: cmd
        run: |
          dir c:\*\MINGW64

