name: Run
on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-verilator
      - uses: dawidd6/action-download-artifact@v2
        with:
         workflow: test.yml
         run_number: 36
         name: Test, Windows 64-bit
         path: C:\Spice64_KLU
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Run
        shell: cmd
        run: |
          copy adc_batch.cir c:\
          copy vlnggen c:\
          copy MSVC.cmd C:\Spice64_KLU\share\ngspice\scripts
          copy verilated.mk d:\a\_temp\msys64\mingw64\share\verilator\include
          cd \
          C:
          md \mingw64\share\verilator\include\vltstd
          copy d:\a\_temp\msys64\mingw64\share\verilator\include\*.* \mingw64\share\verilator\include
          copy d:\a\_temp\msys64\mingw64\share\verilator\include\vltstd\*.* \mingw64\share\verilator\include\vltstd
          md \mingw64\share\verilator\bin
          copy d:\a\_temp\msys64\mingw64\share\verilator\bin\*.* \mingw64\share\verilator\bin
          copy d:\a\_temp\msys64\mingw64\bin\*.* \mingw64\bin
          echo Running vlnggen
          dir \Spice64_KLU\share\ngspice\scripts\src
          \Spice64_KLU\bin\ngspice -b -o log.txt vlnggen  /Spice64_KLU/share/ngspice/examples/xspice/verilator/adc.v
          type log.txt
          dir  adc_obj_dir
          echo Run directly
          perl c:/mingw64/bin/verilator --Mdir adc_obj_dir --prefix Vlng --CFLAGS -IC:/Spice64_KLU/bin/../share/ngspice/scripts/src --CFLAGS -I/c/Spice64_KLU//share/ngspice/scripts/src --compiler msvc --cc --build --exe C:/Spice64_KLU/bin/../share/ngspice/scripts/src/verilator_main.cpp C:/Spice64_KLU/bin/../share/ngspice/scripts/src/verilator_shim.cpp /Spice64_KLU/share/ngspice/examples/xspice/verilator/adc.v
          dir   \Spice64_KLU\share\ngspice\examples\xspice\verilator
          dir   \Spice64_KLU\share\ngspice\examples\xspice\verilator\adc_obj_dir
          echo Testing ...
          \Spice64_KLU\bin\ngspice -b -o log.txt -r adc.raw adc_batch.cir
          type log.txt
          del adc.DLL
          echo Try CL.
          cd adc_obj_dir
          \Spice64_KLU\share\ngspice\scripts\MSVC.CMD
          dir
          cd ..
          \Spice64_KLU\bin\ngspice -b -o log.txt -r adc_msvc.raw \adc_batch.cir
          type log.txt
          md results
          copy *.raw results
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: c:\results
