name: Run
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-verilator
      - uses: dawidd6/action-download-artifact@v2
        with:
         workflow: test.yml
         run_number: 22
         name: Test, Windows 64-bit
         path: C:\Spice64_KLU
      - name: Run
        shell: msys2 {0}
        run: |
          cd C:/Spice64_KLU/share/ngspice/verilog/verilator
          ls
          /Spice64_KLU/bin/ngspice.exe -b -o log.txt sogen.sp ../../examples/xspice/verilog/adc.v
          ls
          cat log.txt
