name: Run
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: windows-latest
    steps:
      - uses: dawidd6/action-download-artifact@v8
        with:
          repo: gatk555/test
          workflow: win_dev.yml
          name: Dev, Windows 64-bit
          path: C:\Spice64
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Run
        shell: cmd
        run: |
          C:
          cd \Spice64\examples\shared
          CL.EXE /O2 /I..\..\include shx.c
          shx -l ..\..\bin-dll\ngspice.dll < t.shx
          md results
          copy *.raw results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: c:\spice64\examples\shared\results
