name: Run
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: mingw-w64-x86_64-verilator
      - name: Run
        shell: msys2 {0}
        run: |
          which verilator
          echo Listing of /c
          ls /c
          echo Listing of /c/msys64/
          ls /c/msys64/
          echo Listing of /d
          ls /d
