name: Run MacOS
on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
         workflow: macos.yml
         run_number: 1
         name: Test Macos X86_64
         path: /usr/local
      - name: Install Dependencies
        run: |
          brew install verilator
          brew install ncurses readline libxaw libatomic_ops
      - uses: actions/checkout@v3
      - name: Run
        run: |
          cp verilated.mk.macos /usr/local/share/verilator/include/verilated.mk
          cp vlnggen /usr/local/share/scripts
          chmod a+x /usr/local/bin/ngspice
          ngspice -b vlnggen /usr/local/share/ngspice/examples/xspice/verilator/adc.v
          ls  adc_obj_dir
          mv adc.so adc.DLL
          echo Testing ...
          ngspice -b -r adc.raw adc_batch.cir
          mkdir ~/results
          cp *.raw ~/results
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: ~/results
