name: Run MacOS
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-12
    steps:
      - uses: dawidd6/action-download-artifact@v3
        with:
         workflow: macos.yml
         run_number: 8
         name: Test Macos X86_64
         path: /usr/local
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: macos.yml
         run_number: 8
         name: Icarus Verilog with libvvp, Mac OS
         path: /usr/local
      - uses: actions/checkout@v4
      - name: Run
        run: |
          chmod a+x /usr/local/bin/ngspice
          echo Testing ...
          ngspice -b -r adc.raw adc_batch.cir
          mkdir ~/results
          cp *.raw ~/results
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: Results
          path: ~/results
