# Build ngspice with MS Visiual C++ compiler.
name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
      - name: Save script
        shell: cmd
        run: |
          cp aux-cfunc.bat ..
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_debug
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        shell: cmd
        run: |
          cp ..\aux-cfunc.bat visualc\xspice
          set config=Release
          set plat=x64
          set suffix=64
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          echo Running cmpp
          set CMPP_IDIR=src/xspice/icm/analog/divide
          mkdir cmpp_out
          set CMPP_ODIR=./cmpp_out
          visualc\xspice\bin\cmpp.exe -mod
          visualc\xspice\bin\cmpp.exe -ifs
          dir cmpp_out
