name: Test
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v3
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - uses: microsoft/setup-msbuild@v1.1
      - name: Build
        shell: cmd
        run: |
          set config=Release
          set plat=x64
          set suffix=64
          md c:\Spice%suffix%\share\ngspice\include\ngspice 
          copy src\include\ngspice\cmtypes.h c:\Spice%suffix%\share\ngspice\include\ngspice
          copy src\include\ngspice\cosim.h c:\Spice%suffix%\share\ngspice\include\ngspice
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\analog.vcxproj
          msbuild %opt% visualc\xspice\digital.vcxproj
          msbuild %opt% visualc\xspice\spice2poly.vcxproj
          msbuild %opt% visualc\xspice\table.vcxproj
          msbuild %opt% visualc\xspice\xtradev.vcxproj
          msbuild %opt% visualc\xspice\xtraevt.vcxproj
          set cms=codemodels\%plat%\%config%
          md visualc\%cms%
          move visualc\xspice\%cms%\*.cm visualc\%cms%
          msbuild %opt% visualc\vngspice.vcxproj
          xcopy /s /i examples c:\Spice%suffix%\share\ngspice\examples
          xcopy /i src\xspice\verilog\*.* c:\Spice%suffix%\share\ngspice\verilog\verilator
      - name: Save
        uses: actions/upload-artifact@v3
        with:
          name: Test, Windows 64-bit
          path: C:\Spice64
