name: Test Verilator MacOS and Windows
on:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >
            mingw-w64-ucrt-x86_64-verilator mingw-w64-ucrt-x86_64-perl
      - uses: actions/checkout@v6
      - uses: dawidd6/action-download-artifact@v8
        with:
         repo: gatk555/test
         workflow: others.yml
         name: Ngspice Test, Windows X86-64
         path: C:\Spice64
         workflow_conclusion: ""
      - name: Soundfiles
        shell: cmd
        run: |
          cd ..
          curl.exe -L -O "https://github.com/libsndfile/libsndfile/releases/download/1.2.2/libsndfile-1.2.2-win64.zip"
          unzip libsndfile-1.2.2-win64.zip
          move libsndfile-1.2.2-win64\bin\sndfile.dll c:\Spice64\bin
          curl.exe -L -O "https://github.com/libsndfile/libsamplerate/releases/download/0.2.2/libsamplerate-0.2.2-win64.zip"
          unzip libsamplerate-0.2.2-win64.zip
          move libsamplerate-0.2.2-win64\bin\samplerate.dll c:\Spice64\bin
      - name: Run in MSYS
        shell: msys2 {0}
        run: |
          echo $PATH
          echo Testing ...
          c:\spice64\bin\ngspice_con vlnggen adc.v
          ls
          c:\spice64\bin\ngspice_con -b -r adc.raw adc_batch.cir
          mkdir results
          copy *.raw ~/results
      - name: Run in CMD
        run: |
          echo %PATH%
          dir c:\mingw64
          dir c:\mingw64\bin
          echo Testing ...
          c:\spice64\bin\ngspice_con vlnggen adc.v
          dir
          c:\spice64\bin\ngspice_con -b -r adc.raw adc_batch.cir
          mkdir results
          copy *.raw ~/results
      - name: Save
        uses: actions/upload-artifact@v6
        with:
          name: Results_Macos
          path: results
