name: Test Verilator MacOS
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-latest
    steps:
      - name: Install Dependencies
        run: |
          brew install libxaw verilator
      - uses: dawidd6/action-download-artifact@v8
        with:
         repo: gatk555/ngspice
         workflow: others.yml
         name: Ngspice pre-master-47, Macos ARM64
         path: /usr/local
         skip_unpack: true
      - uses: actions/checkout@v6
      - name: Run
        run: |
          set sd=`pwd`
          cd /usr/local/
          unzip $sd/'Ngspice pre-master-47, Macos ARM64.zip'
          cd $sd
          chmod a+x /usr/local/bin/ngspice
          echo Testing ...
          ngspice vlnggen adc.v
          ngspice -b -r adc.raw adc_batch.cir
          mkdir ~/results
          cp *.raw ~/results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: ~/results
