name: test VVP - Windows
on:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    name: VVP Windows
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: UCRT64
    steps:
      - name: Tweak git
        shell: bash
        run: git config --global core.autocrlf input
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            autotools
            base-devel
            binutils
            gcc
            git
            gperf
            python-pip
            mingw-w64-ucrt-x86_64-toolchain
      - uses: actions/setup-python@v4
        with:
          python-version: '>=3.5'
      - uses: actions/checkout@v4
        with:
          repository: steveicarus/iverilog
          ref: master
      - name: Build and check
        run: |
          sh autoconf.sh
          ./configure --enable-libvvp --prefix=C:\\ivl
          make -j$(nproc) check
          make install
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Iverilog with libvvp, Windows 64-bit (UCRT64)
          path: C:\ivl
      - name: Package
        run: |
          cd msys2
          makepkg-mingw --noconfirm --noprogressbar -sCLf
      - uses: actions/upload-artifact@v4
        with:
          name: Iverilog with libvvp, MSYS (UCRT64) package for Windows 64-bit
          path: msys2/*.zst
      - name: Test
        run: |
          export PATH=$PATH:/c/ivl/bin
          cp /c/ivl/lib/libvvp.DLL /c/ivl/bin
          echo Do not run./.github/test.sh
