name: test VVP
on:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    name: VVP Windows
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.msystem }}
    steps:
      - name: Tweak git
        shell: bash
        run: git config --global core.autocrlf input
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: >
            git
            base-devel
            gperf
            python-pip
            mingw-w64-${{ matrix.arch }}-toolchain
      - uses: actions/setup-python@v4
        with:
          python-version: '>=3.5'
      - uses: actions/checkout@v3
        with:
          repository: gatk555/iverilog
          ref: libvvp
      - name: Build and check
        run: |
          sh autoconf.sh
          ./configure
          make -j$(nproc) check
          sudo make install
      - name: Install
        run: make install
      - name: Test
        run: ./.github/test.sh
