name: test VVP - Windows
on:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    name: VVP Windows
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: MINGW64
    steps:
      - name: Tweak git
        shell: bash
        run: git config --global core.autocrlf input
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            autotools
            base-devel
            binutils
            gcc
            git
            gperf
            python-pip
      - uses: actions/setup-python@v4
        with:
          python-version: '>=3.5'
      - uses: actions/checkout@v4
        with:
          repository: steveicarus/iverilog
          ref: master
      - name: Build and check
        run: |
          sh autoconf.sh
          ./configure --host=x86_64-w64-mingw32 --enable-libvvp --prefix=C:\\ivl
          mingw32-make -j$(nproc) check
          sudo make install
      - name: Install
        run: make install
      - name: Test
        run: ./.github/test.sh
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Iverilog with libvvp, Windows 64-bit
          path: C:\ivl
