name: Run VVP on Win64

on:
  workflow_dispatch:

jobs:

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 }
        ]
    name: 🟪 ${{ matrix.msystem}} · ${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.msystem }}
    steps:

      - uses: dawidd6/action-download-artifact@v2
        with:
         workflow: vvp_test.yml
         run_number: 7
         workflow_conclusion: ""
         name: MINGW64-x86_64
         path: .
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
      - name: Install
        run: pacman -U --noconfirm *.zst
      - name: Copy
        run: |
          which vvp
          cp /mingw64/lib/libvvp.DLL /mingw64/bin
      - uses: actions/checkout@v3
        with:
          repository: gatk555/iverilog
          ref: libvvp
      - name: Test
        run: |
          vvp ./vvp/examples/hello.vvp
          ./.github/test.sh

