name: Build iverilog - Mac
on:
  workflow_dispatch:
jobs:
  build-mac-arm:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v6
        with:
          repository: steveicarus/iverilog
          ref: master
      - name: Install dependencies
        run: |
          brew install automake bison
      - name: Build, check and install
        run: |
          export PATH="/opt/homebrew/opt/bison/bin:$PATH"
          sh autoconf.sh
          ./configure --enable-libvvp
          make -j$(nproc)
          sudo make install
          make check
      - name: Extract
        run: |
          mkdir -p save/bin save/lib save/include save/man/man1
          cp /usr/local/bin/iveri* save/bin
          cp /usr/local/bin/vvp save/bin
          cp /usr/local/include/iverilog/* save/include
          cp -r /usr/local/lib/ivl save/lib
          for i in libvpi.a libvvp.so libveriuser.a ; do cp /usr/local/lib/$i save/lib ; done
          for i in iverilog.1 iverilog-vpi.1 vvp.1 ; do cp /usr/local/man/man1/$i save/man/man1 ; done
      - name: Save
        uses: actions/upload-artifact@v6
        with:
          name: Icarus Verilog with libvvp, MacOS/ARM64
          path: save

  build-macos-x86_64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v6
        with:
          repository: steveicarus/iverilog
          ref: master
      - name: Install Dependencies
        run: |
          brew install bison
      - name: Build, check and install
        run: |
          export PATH="/opt/homebrew/opt/bison/bin:$PATH"
	  which bison
          autoconf
          ./configure --enable-libvvp
          make -j$(nproc)
          sudo make install
          make check
      - name: Extract
        run: |
          mkdir -p save/bin save/lib save/include save/man/man1
          cp /usr/local/bin/iveri* save/bin
          cp /usr/local/bin/vvp save/bin
          cp /usr/local/include/iverilog/* save/include
          cp -r /usr/local/lib/ivl save/lib
          for i in libvpi.a libvvp.so libveriuser.a ; do cp /usr/local/lib/$i save/lib ; done
          for i in iverilog.1 iverilog-vpi.1 vvp.1 ; do cp /usr/local/man/man1/$i save/man/man1 ; done
      - name: Save
        uses: actions/upload-artifact@v6
        with:
          name: Icarus Verilog with libvvp, MacOS/X64
          path: save

