name: Run VVP on Win64

on:
  workflow_dispatch:

jobs:

  win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include: [
          { msystem: MINGW64, arch: x86_64 }
        ]
    name: ${{ matrix.msystem}} · ${{ matrix.arch }}
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: ${{ matrix.msystem }}
    steps:

      - uses: dawidd6/action-download-artifact@v3
        with:
         workflow: win_dev.yml
         run_number: 19
         name: Dev, Windows 64-bit
         path: C:\Spice64
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: win.yml
         run_number: 3
         workflow_conclusion: ""
         name: MINGW64-x86_64
         path: .
         github_token: ${{secrets.GITHUB_TOKEN}}
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
      - name: Install
        run: pacman -U --noconfirm *.zst
      - name: Copy
        run: |
          which vvp
          ls /mingw64/bin
          which iverilog
          cp /mingw64/lib/libvvp.DLL /mingw64/bin
          mkdir -p /msys64/mingw64/lib
          mv /mingw64/lib/ivl /msys64/mingw64/lib
      - uses: actions/checkout@v3
      - name: Test
        run: |
          C:\Spice64\bin\ngspice -b -r adc.raw adc_batch.cir
          mkdir ~/results
          cp *.raw ~/results
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Results
          path: ~/results

