name: test VVP
on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: gatk555/iverilog
          ref: libvvp
      - name: Install dependencies
        run: |
          brew install bison
          pip3 install docopt
      - name: Build, check and install
        run: |
          export PATH="/usr/local/opt/bison/bin:$PATH"
          autoconf
          ./configure
          make -j$(nproc) check
          sudo make install
    - name: Test
      run: ./.github/test.sh
