# Build ngspice with MS Visiual C++ compiler.
name: Win_Dev
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_dev
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        shell: cmd
        run: |
          set config=Release
          set plat=x64
          set suffix=64
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\digital.vcxproj
          set cms=codemodels\%plat%\%config%
          md visualc\%cms%
          move visualc\xspice\%cms%\*.cm visualc\%cms%
