# Build ngspice with MS Visiual C++ compiler.
name: Win_Dev
on:
  workflow_dispatch:

jobs:
  build-VisualC:
    runs-on: windows-latest
    steps:
      - name: Flex and Bison
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - uses: microsoft/setup-msbuild@v2
      - name: Build
        shell: cmd
        run: |
          set config=Release
          set plat=x64
          set suffix=64
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\cmpp\cmpp.vcxproj
          msbuild %opt% visualc\xspice\analog.vcxproj
          msbuild %opt% visualc\xspice\digital.vcxproj
          msbuild %opt% visualc\xspice\spice2poly.vcxproj
          msbuild %opt% visualc\xspice\table.vcxproj
          msbuild %opt% visualc\xspice\xtradev.vcxproj
          msbuild %opt% visualc\xspice\xtraevt.vcxproj
          set cms=codemodels\%plat%\%config%
          md visualc\%cms%
          move visualc\xspice\%cms%\*.cm visualc\%cms%
          msbuild %opt% visualc\KLU/KLU_COMPLEX.vcxproj
          set config=console_release
          set opt=-property:Configuration=%config% -property:Platform=%plat%
          msbuild %opt% visualc\vngspice.vcxproj
          xcopy /s /i examples\xspice c:\Spice%suffix%\share\ngspice\examples\xspice
      - uses: actions/checkout@v4
      - name: Add DLL end examples
        shell: cmd
        run: |
          unzip libomp.zip
          copy libomp140.x86_64.dll C:\Spice64\bin\vcomp140.dll
          xcopy /i examples\xspice\ghdl C:\Spice64\examples
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Dev, Windows 64-bit
          path: C:\Spice64
  build-win_msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          update: true
          install: >
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            autotools
      - name: Flex and Bison
        shell: cmd
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - name: Build
        run: |
          ./autogen.sh
          mkdir release
          cd release
          ../configure --enable-cider prefix="C:/Spice64" CFLAGS="-m64 -O2" LDFLAGS="-m64 -s"
          make
          cd ..
          echo Create README.ngspice
          echo This binary build of ngspice was built at https://github.com/gatk555/ngspice. > C:\Spice64\README.ngspice
          echo The source code came from the pre-master-44 branch. >> C:\Spice64\README.ngspice
          echo Install to C:\Spice64\. >> C:\Spice64\README.ngspice
      - uses: actions/checkout@v4
        with:
          repository: gatk555/test
      - name: Add DLL and examples
        shell: cmd
        run: |
          unzip libomp.zip
          copy libomp140.x86_64.dll C:\Spice64\bin\vcomp140.dll
          xcopy /i examples\xspice\ghdl C:\Spice64\examples
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice dev, Windows 64-bit console version with MSYS and UCRT64
          path: C:\Spice64
