# Build ngspice with MINGW64
name: Win_Dev_Msys
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: MINGW64
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autotools
      - uses: dawidd6/action-download-artifact@v3
        with:
         repo: gatk555/iverilog
         workflow: win.yml
         run_number: 3
         workflow_conclusion: ""
         name: MINGW64-x86_64
         path: .
         github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Install
        run: pacman -U --noconfirm *.zst
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: hack
      - name: Build
        run: |
          ./autogen.sh
          ls -l
          mkdir release
          cd release
          ../configure --enable-xspice --enable-klu --enable-openmp --enable-osdi --enable-predictor --with-readline=no --disable-debug prefix="C:/Spice64" CFLAGS="-m64 -O2" LDFLAGS="-m64 -s"
          make || echo Failed!
          ls -l src/xspice/verilog
          ls -l src/xspice/verilog/.libs
      - name: Look
        shell: cmd
        run: dir
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Debris
          path: D:\a\test\test\release\src\xspice\verilog
