# Build ngspice with MINGW64
name: Win_Dev_Msys
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: MINGW64
    steps:
      - name: Flex and Bison
        shell: cmd
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autotools libreadline-devel mingw-w64-x86_64-ncurses
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_dev
      - name: Build
        run: |
          ./autogen.sh
          mkdir release
          cd release
          ../configure --with-wingui=no  prefix="C:/Spice64" CFLAGS="-m64 -O2" LDFLAGS="-m64 -s"
          make
          make install
          ldd release/src/ngspice.exe || true
      - uses: actions/checkout@v4
      - name: Add DLL
        shell: cmd
        run: |
          unzip libomp.zip
          copy libomp140.x86_64.dll C:\Spice64\bin\vcomp140.dll
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Dev, Windows 64-bit, MINGW64
          path: C:\Spice64
