# Build ngspice with MINGW64
name: Win_Dev_Msys
on:
  workflow_dispatch:

jobs:
  build-win_msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            autotools
      - name: Flex and Bison
        shell: cmd
        run: |
          md ..\flex-bison
          cd ..\flex-bison
          curl.exe -L -O "https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip"
          unzip win_flex_bison-2.5.25
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: ga_test
      - name: Build
        run: |
          ./compile_min.sh
          cp /ucrt64/bin/libgomp-1.dll /C/Spice64/bin
          cp /ucrt64/bin/libstdc++-6.dll /C/Spice64/bin
          cp /ucrt64/bin/libgcc_s_seh-1.dll /C/Spice64/bin
          cp /ucrt64/bin/libwinpthread-1.dll /C/Spice64/bin
          echo Create README.ngspice
          echo 'This binary package of an Ngspice release was built at https://github.com/gatk555/ngspice.' > /C/Spice64/README.ngspice
          echo The source code came from the ga_test branch. >> /C/Spice64/README.ngspice
          echo Install to C:\\Spice64. >> /C/Spice64/README.ngspice
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: Ngspice Test, Windows 64-bit with MSYS and UCRT64
          path: C:\Spice64
