# Build ngspice with MINGW64
name: Win_Dev_Msys
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      MINGW_ARCH: MINGW64
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
            autotools
      - uses: actions/checkout@v4
        with:
          repository: gatk555/ngspice
          ref: hack
      - name: Build
        run: |
          ./autogen.sh
          ls -l
          mkdir release
          cd release
          ../configure --enable-xspice --enable-klu --enable-openmp --enable-osdi --enable-predictor --with-readline=no --disable-debug prefix="C:/Spice64" CFLAGS="-m64 -O2" LDFLAGS="-m64 -s"
          make || echo Build failed!
          ls -l src/xspice/verilog
          ls -l src/xspice/verilog/.libs
          file  src/xspice/verilog/.libs/*
          make install || echo Install failed!
          ls -l /c/spice64/lib/ngspice
