name: Build libsimavr on Windows (MSYS2 UCRT64)
on: [workflow_dispatch]

jobs:
  ucrt64:
    name: Build libsimavr on Windows (MSYS2 UCRT64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: gatk555/simavr
          ref: test

      - name: Set up MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >
            base-devel
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-libelf
            mingw-w64-ucrt-x86_64-libdwarf
            mingw-w64-ucrt-x86_64-pkgconf
            mingw-w64-ucrt-x86_64-avr-toolchain
            mingw-w64-ucrt-x86_64-freeglut

      - name: Build libsimavr
        run: |
          make
          mkdir simavr_installed
          make -k install-all DESTDIR=$(pwd)/simavr_installed/ || true
          mv simavr_installed/bin/simavr simavr_installed/bin/simavr.exe
          file simavr_installed/bin/*
          ldd simavr_installed/bin/simavr.exe
          ldd simavr_installed/examples/charlcd.elf
          cp /ucrt64/bin/libwinpthread-1.dll simavr_installed/examples
          cp /ucrt64/bin/libfreeglut.dll simavr_installed/examples
      - uses: microsoft/setup-msbuild@v3
      - name: dumpbin
        shell: cmd
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx86\x64\dumpbin" /dependents simavr_installed\bin\simavr.exe
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.44.35207\bin\Hostx86\x64\dumpbin" /dependents simavr_installed\examples\charlcd.elf
      - name: Tests
        run: |
          which avr-gcc | true
          cd tests
          make run_tests
      - uses: actions/upload-artifact@v6
        with:
          name: Windows 64-bit
          path: simavr_installed
